*** empty log message ***

diff --git a/config/functions/config_gip_sge b/config/functions/config_gip_sge
--- a/config/functions/config_gip_sge
+++ b/config/functions/config_gip_sge
@@ -45,6 +45,11 @@ INSTALL_ROOT=${INSTALL_ROOT:-/opt}
 
 yaimlog DEBUG "Get gLite version "
 
+
+###
+### Get glite version
+###
+
 glite_version=`/opt/glite/bin/glite-version | cut -d '.' -f1-2`
 if [ "X$glite_version" == "X" -o "X$glite_version" != "X3.1" ]; then
    yaimlog ABORT "gLite version not supported. Exiting..."
@@ -53,14 +58,23 @@ else
    yaimlog DEBUG "Running SGE Information Provider configuration for gLite version >= 3.1"
 fi
 
+
+#---*---
+
+
+###
+### General checks regarding Information Plugin
+###
+
 yaimlog INFO "Build InfoProvider based on LeSC implementation"
 
-SGE_INFOPROVIDER_DIR=/etc/sge-jobmanager
-SGE_INFOPROVIDER_VQUEUES=${SGE_INFOPROVIDER_DIR}/vqueues.conf
-SGE_INFOPROVIDER_REPORTER=${SGE_INFOPROVIDER_DIR}/info-reporter.conf
-SGE_INFOPROVIDER_CLUSTER=${SGE_INFOPROVIDER_DIR}/cluster.state
+SGE_OLD_INFOPROVIDER=$INSTALL_ROOT/lcg/libexec/lcg-info-dynamic-sge
+SGE_INFOPROVIDER=$INSTALL_ROOT/lcg/libexec/sge_helper
 
-SGE_INFOPROVIDER=$INSTALL_ROOT/lcg/libexec/lcg-info-dynamic-sge
+if [ -e ${SGE_OLD_INFOPROVIDER} ]; then
+     yaimlog WARNING "A new implementation of SGE InfoProvider is available. ${SGE_OLD_INFOPROVIDER} will not be used anymore."
+fi
+
 if [ ! -e ${SGE_INFOPROVIDER} ]; then
    yaimlog ABORT " SGE InfoProvider is not installed !!! Without it the information system will not work ! Exiting ... "
    exit 1
@@ -74,7 +88,7 @@ if [ -e ${SGE_INFOPROVIDER}.rpmsave ]; then
    yaimlog WARNING "Previous ${SGE_INFOPROVIDER} is saved as .rpmsave. New ${SGE_INFOPROVIDER} is in place."
 fi
 
-yaimlog DEBUG "Check $SGE_INFOPROVIDER file permissions"
+yaimlog DEBUG "Check ${SGE_INFOPROVIDER} file permissions"
 if [ -x ${SGE_INFOPROVIDER} ]; then
      yaimlog DEBUG "${SGE_INFOPROVIDER} has correct permissions"
 else
@@ -82,49 +96,34 @@ else
      chmod 755 $SGE_INFOPROVIDER
 fi
 
+
 #---*---
 
+
+###
+### Build /etc/sge-jobmanager/vqueues
+###
+
+SGE_INFOPROVIDER_DIR=/etc/sge-jobmanager
 if [ ! -d ${SGE_INFOPROVIDER_DIR} ]; then
    mkdir ${SGE_INFOPROVIDER_DIR}
 fi 
 
 yaimlog DEBUG "Creating ${SGE_INFOPROVIDER_VQUEUES} file..."
+SGE_INFOPROVIDER_VQUEUES=${SGE_INFOPROVIDER_DIR}/vqueues.conf
 if [ -e ${SGE_INFOPROVIDER_VQUEUES} ]; then
-   count=`ls -tr ${SGE_INFOPROVIDER_VQUEUES}.OLD* 2>/dev/null | tail -n 1 | cut -f4 -d"."`
-   if [ "X$count" == "X" ]; then
-       count=0
-   else
-       count=`expr $count + 1`
+   yaimlog WARNING "${SGE_INFOPROVIDER_VQUEUES} exists. It will not be changed!"
+   SGE_INFOPROVIDER_VQUEUES="/tmp/sge/etc/sge-jobmanager/vqueues.conf"
+   if [ ! -d /tmp/sge/etc/sge-jobmanager ]; then
+        mkdir -p /tmp/sge/etc/sge-jobmanager
+        chmod 700 /tmp/sge/etc/sge-jobmanager
    fi
-   mv -f ${SGE_INFOPROVIDER_VQUEUES} ${SGE_INFOPROVIDER_VQUEUES}.OLD.${count}
+   yaimlog WARNING "A recommended configuration will be created under ${SGE_INFOPROVIDER_VQUEUES}. You can copy it manually!"        
 fi
 
 cat <<EOF_SGE_INFOPROVIDER_VQUEUES >> ${SGE_INFOPROVIDER_VQUEUES}
 #
 # SGE JobManager queue mapping file
-#
-# It is sometimes desirable to be able to override various RSL properties of
-# jobs submitted to Globus based on the name of the queue that was requested.
-#
-# For example, LCG 2_6_0 resource brokers only allow an end user to specify
-# a particular queue or set of queues for a job to be submitted to, but not
-# to specify any other details about the job, such as how long it will take
-# to execute.
-#
-# This file allows you to override the properties of a job based on the name
-# of the logical queue that it was submitted to.
-#
-# Set of properties you can manipulate:
-# ------------------------------------
-# queue:                Set the target queue to submit to.
-#                       NOTE: All property matches will match against the
-#                             originally specified queue, not the new queue.
-# max_cpu_time:         Hard CPU time limit, in minutes.
-# max_wall_time:        Hard wallclock time limit, in minutes.
-#
-# (There is undocumented support for other fields.)
-#
-# Spaces are currently not permitted as any value.
 #
 # Virtual
 # Queue         Property                New Value
@@ -137,231 +136,148 @@ $QUEUE          queue                   $QUEUE
 EOF_SGE_INFOPROVIDER_VQUEUES
 done
 
-if [ "X$count" != "X" ]; then
-   diff ${SGE_INFOPROVIDER_VQUEUES}.OLD.${count} ${SGE_INFOPROVIDER_VQUEUES} > /dev/null 2>&1
-fi
-if [ $? == 0 ]; then
-     rm -f ${SGE_INFOPROVIDER_VQUEUES}.OLD.${count}
-else
-     echo " ${SGE_INFOPROVIDER_VQUEUES} exists. Your old file will be saved as ${SGE_INFOPROVIDER_VQUEUES}.OLD.${count}"
-fi
-
-count=""
+chmod 644 ${SGE_INFOPROVIDER_VQUEUES}
 
 
 #---*---
 
+
+###
+### Build info-reporter.conf file
+###
+
+SGE_INFOPROVIDER_REPORTER=${SGE_INFOPROVIDER_DIR}/info-reporter.conf
 yaimlog DEBUG "Creating $SGE_INFOPROVIDER_REPORTER file..."
 if [ -e ${SGE_INFOPROVIDER_REPORTER} ]; then
-   count=`ls -tr ${SGE_INFOPROVIDER_REPORTER}.OLD* 2>/dev/null | tail -n 1 | cut -f4 -d"."`
-   if [ "X$count" == "X" ]; then
-       count=0
-   else
-       count=`expr $count + 1`
-   fi
-   mv -f ${SGE_INFOPROVIDER_REPORTER} ${SGE_INFOPROVIDER_REPORTER}.OLD.${count}
+   yaimlog WARNING "${SGE_INFOPROVIDER_VQUEUES} exists. It will not be changed!"
+   ${SGE_INFOPROVIDER_VQUEUES}="/tmp/sge/etc/sge-jobmanager/info-reporter.conf"
+   yaimlog WARNING "A recommended configuration will be created under ${SGE_INFOPROVIDER_REPORTER}. You can copy it manually!"
 fi
 
 cat <<EOF_SGE_INFOPROVIDER_REPORTER >> ${SGE_INFOPROVIDER_REPORTER}
 #
 # Sample configuration file for SGE information reporter
 # ======================================================
-#
-# The default location of this file is /etc/sge-jobmanager/info-reporter.conf
-# however this can be overriden on the command line
-
-# Default values are shown below
-
-##############################################################################
-# SGE Environment Variables...
-
 SGE_ROOT = $SGE_ROOT
 SGE_ARCH = `$SGE_ROOT/util/arch`
 SGE_CELL = $SGE_CELL
-
-##############################################################################
-# Override location of SGE commands...
-# The default values are calculated using the environment variables above
-# so these configuration values shouldn't normally need to be specified
-
-# qconf_command =
-# qstat_command =
-# qselect_command =
-
-##############################################################################
-# Location of static LDIF file...
-
 ldif_file = $INSTALL_ROOT/glite/etc/gip/ldif/static-file-CE.ldif
-
-##############################################################################
-# Location of SGE jobmanager virtual queue mapping configuration file
-
 vqueue_file = /etc/sge-jobmanager/vqueues.conf
-
-##############################################################################
-# Location of file defining current cluster state
-# This file should contain one of the following strings:
-#     Production, Draining, Queueing, Closed
-
 state_file = /etc/sge-jobmanager/cluster.state
-
-##############################################################################
-# Regular expressions matching SGE "queue instances" (ie: queue@hostname)
-# that should be included/excluded from our calculations...
-#
-# Default is to include everything and exclude nothing
-# Specifying these values may distort the estimated response times
-
-# queue_include_regexp = ^.*$
-# queue_exclude_regexp =
-
-##############################################################################
-# Regular expressions matching usernames that should be included/excluded
-# from our calculations
-#
-# Default is to include everything and exclude nothing
-# Specifying these values may distort the estimated response times
-
-# user_include_regexp = ^.*$
-# user_exclude_regexp =
-
-##############################################################################
-# Job efficiency
-# Used to convert cpu-time limits into estimated wallclock runtimes
-# eg:  1.0 would specify that jobs typically run at 100% efficiency
-#          and therefore the wallclock runtime equals the cpu time
-#      0.6 would specify that jobs typically only run at 60% efficiency
-
-# job_efficiency = 0.9
-
-##############################################################################
-# Default duration of jobs for which a time limit cannot be determined
-# Can be specified as <seconds>, <hours>:<minutes>:<seconds>
-#     or <days>:<hours>:<minutes>:<seconds>
-
-# default_duration = 7:00:00:00
-
-##############################################################################
-# Configuration options for mapping logins/groups to VOs...
-# 
-# passwd_file & group_file should only be specified if you DON'T want to
-# use perl's built-in functions for looking up login names and groups
-#
-# eg: because the accounts don't exist on the machine on which the
-#     information provider is being run
-
-# passwd_file=/etc/passwd
-# group_file=/etc/group
-
-# The following is only required where members of a VO have a login group
-# that is different from the name of the VO
-#
-# group <group>=<vo>          eg:  group ngs=ngs.ac.uk
-
-# The following is only required where the VO mapping needs to be overriden
-# on a per-login basis
-#
-#
-# login <login>=<vo>          eg:  login ngs001=ngs.ac.uk
-
-##############################################################################
-# File in which to capture information used by the information reporter
-# to generate its results.
-# Information from this file can be converted into test data to allow the
-# calculations to be replayed for debugging/development purposes
-# Once created, the file will not be overwritten
-# If a fresh capture is required, then the filename should be changed
-# or the file should be deleted
-
-# capture_file = capture_file_22012007
 EOF_SGE_INFOPROVIDER_REPORTER
 
-if [ "X$count" != "X" ]; then
-   diff ${SGE_INFOPROVIDER_REPORTER}.OLD.${count} ${SGE_INFOPROVIDER_REPORTER} > /dev/null 2>&1
-fi
-if [ $? == 0 ]; then
-     rm -f ${SGE_INFOPROVIDER_REPORTER}.OLD.${count}
-else
-     echo " ${SGE_INFOPROVIDER_REPORTER} exists. Your old file will be saved as ${SGE_INFOPROVIDER_REPORTER}.OLD.${count}"
-fi
-count=""
+chown 644 ${SGE_INFOPROVIDER_REPORTER}
+
 
 #---*---
 
-yaimlog DEBUG "Set Cluster status to Production in $SGE_INFOPROVIDER_CLUSTER"
 
+###
+### Build info-reporter.conf file
+###
+
+SGE_INFOPROVIDER_CLUSTER=${SGE_INFOPROVIDER_DIR}/cluster.state
+yaimlog DEBUG "Set Cluster status to Production in $SGE_INFOPROVIDER_CLUSTER"
 rm -f $SGE_INFOPROVIDER_CLUSTER
 cat <<EOF_SGE_INFOPROVIDER_CLUSTER >> ${SGE_INFOPROVIDER_CLUSTER}
 Production
 EOF_SGE_INFOPROVIDER_CLUSTER
 
+chown 644 ${SGE_INFOPROVIDER_CLUSTER}
+
+
 #---*---
+
+
+###
+### Set /glite/etc/gip/plugin/glite-info-dynamic-ce
+###
 
 CE_PLUGIN_FILE=${INSTALL_ROOT}/glite/etc/gip/plugin/glite-info-dynamic-ce
 yaimlog DEBUG "Configure SGE dynamic information plugin: ${CE_PLUGIN_FILE}"
 if [ -e ${CE_PLUGIN_FILE} ]; then
    rm -f ${CE_PLUGIN_FILE}
 fi 
-plugin=${INSTALL_ROOT}/lcg/libexec/lcg-info-dynamic-sge
 cat <<EOF_CE_PLUGIN_FILE > ${CE_PLUGIN_FILE}
 #!/bin/sh
-$plugin
+/opt/lcg/libexec/lcg-info-dynamic-scheduler -c /opt/glite/etc/lcg-info-dynamic-scheduler.conf
 EOF_CE_PLUGIN_FILE
 
 yaimlog DEBUG "Set proper permissions to ${CE_PLUGIN_FILE}"
 chmod 755 ${CE_PLUGIN_FILE}
 
-#---*---
-
-yaimlog DEBUG "Include dynamic script in /opt/lcg/etc/lcg-info-generic.conf"
-
-GLITE_INFO_GENERIC_CONF=/opt/glite/etc/gip/glite-info-generic.conf
-yaimlog DEBUG "Configuring ${SGE_INFOPROVIDER} in ${GLITE_INFO_GENERIC_CONF} as dynamic script"
-
-if [ ! -e ${GLITE_INFO_GENERIC_CONF} ]; then
-   yaimlog ABORT " $GLITE_INFO_GENERIC_CONF does not exist"
-   exit 1
-fi
-
-dynamic_script_exists=`grep dynamic_script ${GLITE_INFO_GENERIC_CONF}`
-if [ "X$dynamic_script_exists" == "X"  ]; then
-   echo "dynamic_script = /opt/lcg/libexec/lcg-info-dynamic-sge" > /opt/glite/etc/gip/glite-info-generic.conf.tmp
-   cat /opt/glite/etc/gip/glite-info-generic.conf >> /opt/glite/etc/gip/glite-info-generic.conf.tmp
-   mv -f /opt/glite/etc/gip/glite-info-generic.conf.tmp /opt/glite/etc/gip/glite-info-generic.conf
-else
-   yaimlog WARNING "A dynamic script is already configured in ${GLITE_INFO_GENERIC_CONF}"
-   yaimlog WARNING "Rewritting current implementation \"$dynamic_script_exists\" "
-   echo "dynamic_script = /opt/lcg/libexec/lcg-info-dynamic-sge" > /opt/glite/etc/gip/glite-info-generic.conf.tmp
-   cat /opt/glite/etc/gip/glite-info-generic.conf | grep -v dynamic_script >> /opt/glite/etc/gip/glite-info-generic.conf.tmp 
-   mv -f /opt/glite/etc/gip/glite-info-generic.conf.tmp /opt/glite/etc/gip/glite-info-generic.conf
-fi
 
 #---*---
+
+
+###
+### Set /opt/glite/etc/gip/plugin/glite-info-dynamic-scheduler-wrapper
+###
 
 CE_SCHEDULER_WRAPPER_FILE=${INSTALL_ROOT}/glite/etc/gip/plugin/glite-info-dynamic-scheduler-wrapper
-yaimlog WARNING "Comment the content of $CE_SCHEDULER_WRAPPER_FILE. Not used in SGE"
+yaimlog DEBUG ""Configure SGE dynamic scheduler wrapper plugin: ${CE_SCHEDULER_WRAPPER_FILE}"
 if [ -e ${CE_SCHEDULER_WRAPPER_FILE} ]; then
    rm -f ${CE_SCHEDULER_WRAPPER_FILE}
 fi
 cat <<EOF_CE_SCHEDULER_WRAPPER_FILE > ${CE_SCHEDULER_WRAPPER_FILE}
 #!/bin/sh
-# /opt/lcg/libexec/lcg-info-dynamic-scheduler -c /opt/glite/etc/lcg-info-dynamic-scheduler.conf
+/opt/lcg/libexec/sge_helper --info -c /opt/glite/etc/lcg-info-dynamic-scheduler.conf
 EOF_CE_SCHEDULER_WRAPPER_FILE
 
-yaimlog DEBUG "Check ${CE_SCHEDULER_WRAPPER_FILE} file permissions"
-if [ -x ${CE_SCHEDULER_WRAPPER_FILE} ]; then
-     yaimlog DEBUG "${CE_SCHEDULER_WRAPPER_FILE} has correct permissions"
-else
-     yaimlog WARNING "${CE_SCHEDULER_WRAPPER_FILE} does not has the correct permissions. Changing them ..."
-     chmod 755 ${CE_SCHEDULER_WRAPPER_FILE}
-fi
+yaimlog DEBUG "Set proper permissions to ${CE_SCHEDULER_WRAPPER_FILE}"
+chmod 755 ${CE_SCHEDULER_WRAPPER_FILE}
+
 
 #---*---
 
-yaimlog DEBUG "Restart information system after reconfiguring SGE"
 
-/etc/init.d/bdii stop
-/etc/init.d/bdii start
+###
+### SGE Configure /opt/glite/etc/lcg-info-dynamic-scheduler.conf
+###
+
+CONF_FILE="/opt/glite/etc/lcg-info-dynamic-scheduler.conf"
+if [ ! -e ${CONF_FILE} ]; then
+     yaimlog ABORT " The ${CONF_FILE} doesn't exist. Aborting..."
+     exit 1
+fi
+
+LRMS_SECTION=`grep LRMS $CONF_FILE`
+if [ "X${LRMS_SECTION}" != "X[LRMS]" ]; then
+     yaimlog INFO "Adding [LRMS] section to ${CONF_FILE}"
+     echo "[LRMS]" >> ${CONF_FILE}
+fi
+
+LRMS_PLUGIN=`grep lrms_backend_cmd $CONF_FILE | cut -f1 -d ":" | sed 's/ //g'`
+if [ "X${LRMS_PLUGIN}" != "Xlrms_backend_cmd" ]; then
+     yaimlog INFO "Adding lrms_backend_cmd to ${CONF_FILE}"
+     echo "lrms_backend_cmd: /opt/lcg/libexec/sge_helper --lrmsinfo -c /opt/glite/etc/lcg-info-dynamic-scheduler.conf" >> ${CONF_FILE}
+else
+     LRMS_ARG=`grep lrms_backend_cmd $CONF_FILE | cut -f2 -d ":" | sed 's/ //g'`
+     if [ "X${LRMS_ARG}" != "X/opt/lcg/libexec/sge_helper--lrmsinfo-c/opt/glite/etc/lcg-info-dynamic-scheduler.conf" ]; then
+          yaimlog INFO "lrms_backend_cmd not properly configured. Fixing..."
+          sed 's/lrms_backend_cmd.*/lrms_backend_cmd: \/opt\/lcg\/libexec\/sge_helper --lrmsinfo -c \/opt\/glite\/etc\/lcg\-info\-dynamic\-scheduler.conf/g' $CONF_FILE > /tmp/lcg-info-dynamic-scheduler.conf
+           mv -f /tmp/lcg-info-dynamic-scheduler.conf $CONF_FILE
+     fi
+fi
+
+SCHED_SECTION=`grep Scheduler $CONF_FILE`
+if [ "X${SCHED_SECTION}" != "X[Scheduler]" ]; then
+     yaimlog INFO "Adding [Scheduler] section to ${CONF_FILE}"
+     echo "[Scheduler]" >> ${CONF_FILE}
+fi
+
+SCHED_PLUGIN=`grep vo_max_jobs_cmd $CONF_FILE | cut -f1 -d ":" | sed 's/ //g'`
+if [ "X${SCHED_PLUGIN}" != "Xvo_max_jobs_cmd" ]; then
+     yaimlog INFO "Adding vo_max_jobs_cmd to ${CONF_FILE}"
+     echo "vo_max_jobs_cmd: /opt/lcg/libexec/sge_helper --vomaxjobs -c /opt/glite/etc/lcg-info-dynamic-scheduler.conf" >> ${CONF_FILE}
+else
+     SCHED_ARG=`grep vo_max_jobs_cmd $CONF_FILE | cut -f2 -d ":" | sed 's/ //g'`
+     if [ "X${LRMS_ARG}" != "X/opt/lcg/libexec/sge_helper--vomaxjobs-c/opt/glite/etc/lcg-info-dynamic-scheduler.conf" ]; then
+          yaimlog INFO "vo_max_jobs_cmd not properly configured. Fixing..."
+          sed 's/vo_max_jobs_cmd.*/vo_max_jobs_cmd: \/opt\/lcg\/libexec\/sge_helper --vomaxjobs -c \/opt\/glite\/etc\/lcg\-info\-dynamic\-scheduler.conf/g' $CONF_FILE > /tmp/lcg-info-dynamic-scheduler.conf
+           mv -f /tmp/lcg-info-dynamic-scheduler.conf $CONF_FILE
+     fi
+fi
 
 return 0
 
