Changes to EMI

diff --git a/config/functions/config_gip_sge b/config/functions/config_gip_sge
--- a/config/functions/config_gip_sge
+++ b/config/functions/config_gip_sge
@@ -41,28 +41,20 @@ function config_gip_sge_setenv(){
 
 function config_gip_sge(){
 
-INSTALL_ROOT=${INSTALL_ROOT:-/opt}
-
-
 ###
 ### Get glite version
 ###
 
-yaimlog DEBUG "Getting gLite version... "
+yaimlog DEBUG "Getting EMI version... "
 
-glite_version=`/opt/glite/bin/glite-version | cut -d '.' -f1-2`
-if [ "X$glite_version" != "X" ]; then
-   if  [ "X$glite_version" != "X3.1" -a "X$glite_version" != "X3.2" ]; then
-          yaimlog ABORT "gLite version not supported. Exiting..."
-          exit 1
-   fi
-else
-   yaimlog ABORT "Unable to get glite version. Exiting..."
-   exit 1
+emi_version=/etc/emi-version
+
+if [ ! -e ${emi_version} ]; then
+    yaimlog ABORT "EMI version not found Exiting..."
+    exit 1
 fi
 
-yaimlog DEBUG "Running SGE GIP configuration for gLite version $glite_version!"
-
+yaimlog DEBUG "Running SGE Grid Gateway configuration for gLite version $emi_version!"
 
 #---*---
 
@@ -99,7 +91,6 @@ if ( echo " ${NODE_TYPE_LIST} " | egrep -q "CE" ) && ( echo " ${NODE_TYPE_LIST} 
 	fi
 fi
 
-
 #---*---
 
 ###
@@ -108,8 +99,8 @@ fi
 
 yaimlog INFO "Build InfoProvider based on LeSC implementation"
 
-SGE_OLD_INFOPROVIDER=$INSTALL_ROOT/lcg/libexec/lcg-info-dynamic-sge
-SGE_INFOPROVIDER=$INSTALL_ROOT/glite/libexec/sge_helper
+SGE_OLD_INFOPROVIDER=/usr/libexec/lcg-info-dynamic-sge
+SGE_INFOPROVIDER=/usr/libexec/glite-info-dynamic-sge
 
 if [ -e ${SGE_OLD_INFOPROVIDER} ]; then
      yaimlog WARNING "A new implementation of SGE InfoProvider is available. ${SGE_OLD_INFOPROVIDER} will not be used anymore."
@@ -202,9 +193,12 @@ cat <<EOF_SGE_INFOPROVIDER_REPORTER > ${SGE_INFOPROVIDER_REPORTER}
 SGE_ROOT = $SGE_ROOT
 SGE_ARCH = `$SGE_ROOT/util/arch`
 SGE_CELL = $SGE_CELL
-ldif_file = $INSTALL_ROOT/glite/etc/gip/ldif/static-file-CE.ldif
+#ldif_file = $INSTALL_ROOT/glite/etc/gip/ldif/static-file-CE.ldif
+ldif_file = /var/lib/bdii/gip/ldif/static-file-CE.ldif
 vqueue_file = /etc/sge-jobmanager/vqueues.conf
 state_file = /etc/sge-jobmanager/cluster.state
+qstat_command = $SGE_ROOT/bin/`$SGE_ROOT/util/arch`/qstat
+qconf_command = $SGE_ROOT/bin/`$SGE_ROOT/util/arch`/qconf
 EOF_SGE_INFOPROVIDER_REPORTER
 
 chown 644 ${SGE_INFOPROVIDER_REPORTER}
@@ -236,7 +230,8 @@ chown 644 ${SGE_INFOPROVIDER_CLUSTER}
 ### Set /opt/glite/etc/gip/plugin/glite-info-dynamic-ce
 ###
 
-CE_PLUGIN_FILE=${INSTALL_ROOT}/glite/etc/gip/plugin/glite-info-dynamic-ce
+#CE_PLUGIN_FILE=${INSTALL_ROOT}/glite/etc/gip/plugin/glite-info-dynamic-ce
+CE_PLUGIN_FILE=/var/lib/bdii/gip/plugin/glite-info-dynamic-ce
 
 yaimlog DEBUG "Configure SGE dynamic information plugin: ${CE_PLUGIN_FILE}"
 
@@ -245,7 +240,8 @@ if [ -e ${CE_PLUGIN_FILE} ]; then
 fi 
 cat <<EOF_CE_PLUGIN_FILE > ${CE_PLUGIN_FILE}
 #!/bin/sh
-/opt/glite/libexec/sge_helper --info -c /opt/glite/etc/lcg-info-dynamic-scheduler.conf
+#/opt/glite/libexec/sge_helper --info -c /opt/glite/etc/lcg-info-dynamic-scheduler.conf
+/usr/libexec/glite-info-dynamic-sge --info -c /etc/lcg-info-dynamic-scheduler.conf
 EOF_CE_PLUGIN_FILE
 
 yaimlog DEBUG "Set proper permissions to ${CE_PLUGIN_FILE}"
@@ -259,8 +255,7 @@ chmod 755 ${CE_PLUGIN_FILE}
 ### Set /opt/glite/etc/gip/plugin/glite-info-dynamic-scheduler-wrapper
 ###
 
-CE_SCHEDULER_WRAPPER_FILE=${INSTALL_ROOT}/glite/etc/gip/plugin/glite-info-dynamic-scheduler-wrapper
-
+CE_SCHEDULER_WRAPPER_FILE=/var/lib/bdii/gip/plugin/glite-info-dynamic-scheduler-wrapper
 yaimlog DEBUG "Configure SGE dynamic scheduler wrapper plugin: ${CE_SCHEDULER_WRAPPER_FILE}"
 
 if [ -e ${CE_SCHEDULER_WRAPPER_FILE} ]; then
@@ -268,7 +263,8 @@ if [ -e ${CE_SCHEDULER_WRAPPER_FILE} ]; then
 fi
 cat <<EOF_CE_SCHEDULER_WRAPPER_FILE > ${CE_SCHEDULER_WRAPPER_FILE}
 #!/bin/sh
-/opt/lcg/libexec/lcg-info-dynamic-scheduler -c /opt/glite/etc/lcg-info-dynamic-scheduler.conf
+#/opt/lcg/libexec/lcg-info-dynamic-scheduler -c /opt/glite/etc/lcg-info-dynamic-scheduler.conf
+/usr/libexec/lcg-info-dynamic-scheduler -c /etc/lcg-info-dynamic-scheduler.conf
 EOF_CE_SCHEDULER_WRAPPER_FILE
 
 yaimlog DEBUG "Set proper permissions to ${CE_SCHEDULER_WRAPPER_FILE}"
@@ -282,7 +278,8 @@ chmod 755 ${CE_SCHEDULER_WRAPPER_FILE}
 ### SGE Configure /opt/glite/etc/lcg-info-dynamic-scheduler.conf
 ###
 
-CONF_FILE="/opt/glite/etc/lcg-info-dynamic-scheduler.conf"
+#CONF_FILE="/opt/glite/etc/lcg-info-dynamic-scheduler.conf"
+CONF_FILE="/etc/lcg-info-dynamic-scheduler.conf"
 if [ ! -e ${CONF_FILE} ]; then
      yaimlog ABORT " The ${CONF_FILE} does not exist. Aborting..."
      exit 1
@@ -296,14 +293,14 @@ fi
 
 LRMS_PLUGIN=`grep lrms_backend_cmd $CONF_FILE | cut -f1 -d ":" | sed 's/ //g'`
 if [ "X${LRMS_PLUGIN}" != "Xlrms_backend_cmd" ]; then
-     yaimlog INFO "Adding lrms_backend_cmd to ${CONF_FILE}"
-     echo "lrms_backend_cmd: /opt/glite/libexec/sge_helper --lrmsinfo -c /opt/glite/etc/lcg-info-dynamic-scheduler.conf" >> ${CONF_FILE}
+    yaimlog INFO "Adding lrms_backend_cmd to ${CONF_FILE}"
+    echo "lrms_backend_cmd: /usr/libexec/glite-info-dynamic-sge --lrmsinfo -c /etc/lcg-info-dynamic-scheduler.conf" >> ${CONF_FILE}
 else
      LRMS_ARG=`grep lrms_backend_cmd $CONF_FILE | cut -f2 -d ":" | sed 's/ //g'`
-     if [ "X${LRMS_ARG}" != "X/opt/glite/libexec/sge_helper--lrmsinfo-c/opt/glite/etc/lcg-info-dynamic-scheduler.conf" ]; then
+   if [ "X${LRMS_ARG}" != "X/usr/libexec/glite-info-dynamic-sge –lrmsinfo -c /etc/lcg-info-dynamic-scheduler.conf" ]; then
           yaimlog INFO "lrms_backend_cmd not properly configured. Fixing..."
-          sed 's/lrms_backend_cmd.*/lrms_backend_cmd: \/opt\/glite\/libexec\/sge_helper --lrmsinfo -c \/opt\/glite\/etc\/lcg\-info\-dynamic\-scheduler.conf/g' $CONF_FILE > /tmp/lcg-info-dynamic-scheduler.conf
-           mv -f /tmp/lcg-info-dynamic-scheduler.conf $CONF_FILE
+	  sed 's/lrms_backend_cmd.*/lrms_backend_cmd: \/usr\/libexec\/glite\-info\-dynamic\-sge --lrmsinfo -c \/etc\/lcg\-info\-dynamic\-scheduler.conf/g' $CONF_FILE > /tmp/lcg-info-dynamic-scheduler.conf
+          mv -f /tmp/lcg-info-dynamic-scheduler.conf $CONF_FILE
      fi
 fi
 
@@ -315,14 +312,14 @@ fi
 
 SCHED_PLUGIN=`grep vo_max_jobs_cmd $CONF_FILE | cut -f1 -d ":" | sed 's/ //g'`
 if [ "X${SCHED_PLUGIN}" != "Xvo_max_jobs_cmd" ]; then
-     yaimlog INFO "Adding vo_max_jobs_cmd to ${CONF_FILE}"
-     echo "vo_max_jobs_cmd: /opt/glite/libexec/sge_helper --vomaxjobs -c /opt/glite/etc/lcg-info-dynamic-scheduler.conf" >> ${CONF_FILE}
+    yaimlog INFO "Adding vo_max_jobs_cmd to ${CONF_FILE}"
+    echo "vo_max_jobs_cmd: /usr/libexec/glite-info-dynamic-sge --vomaxjobs -c /etc/lcg-info-dynamic-scheduler.conf" >> ${CONF_FILE}
 else
-     SCHED_ARG=`grep vo_max_jobs_cmd $CONF_FILE | cut -f2 -d ":" | sed 's/ //g'`
-     if [ "X${LRMS_ARG}" != "X/opt/glite/libexec/sge_helper--vomaxjobs-c/opt/glite/etc/lcg-info-dynamic-scheduler.conf" ]; then
+    SCHED_ARG=`grep vo_max_jobs_cmd $CONF_FILE | cut -f2 -d ":" | sed 's/ //g'`
+    if [ "X${LRMS_ARG}" != "X/usr/libexec/glite-info-dynamic-sge –vomaxjobs -c /etc/lcg-info-dynamic-scheduler.conf" ]; then
           yaimlog INFO "vo_max_jobs_cmd not properly configured. Fixing..."
-          sed 's/vo_max_jobs_cmd.*/vo_max_jobs_cmd: \/opt\/glite\/libexec\/sge_helper --vomaxjobs -c \/opt\/glite\/etc\/lcg\-info\-dynamic\-scheduler.conf/g' $CONF_FILE > /tmp/lcg-info-dynamic-scheduler.conf
-           mv -f /tmp/lcg-info-dynamic-scheduler.conf $CONF_FILE
+	sed 's/vo_max_jobs_cmd.*/vo_max_jobs_cmd: \/usr\/libexec\/glite-info\-dynamic\-sge --vomaxjobs -c \/etc\/lcg\-info\-dynamic\-scheduler.conf/g' $CONF_FILE > /tmp/lcg-info-dynamic-scheduler.conf
+	mv -f /tmp/lcg-info-dynamic-scheduler.conf $CONF_FILE
      fi
 fi
 
diff --git a/config/functions/config_sgegg b/config/functions/config_sgegg
--- a/config/functions/config_sgegg
+++ b/config/functions/config_sgegg
@@ -48,96 +48,16 @@ INSTALL_ROOT=${INSTALL_ROOT:-/opt}
 ### Get gLite version
 ###
 
-yaimlog DEBUG "Getting gLite version... "
+yaimlog DEBUG "Getting EMI version... "
 
-glite_version=`/opt/glite/bin/glite-version | cut -d '.' -f1-2`
-if [ "X$glite_version" != "X" ]; then
-   if  [ "X$glite_version" != "X3.1" -a "X$glite_version" != "X3.2" ]; then
-          yaimlog ABORT "gLite version not supported. Exiting..."
-          exit 1
-   fi
-else
-   yaimlog ABORT "Unable to get glite version. Exiting..."
-   exit 1
+emi_version=/etc/emi-version
+
+if [ ! -e ${emi_version} ]; then
+    yaimlog ABORT "EMI version not found Exiting..."
+    exit 1
 fi
 
-yaimlog DEBUG "Running SGE Grid Gateway configuration for gLite version $glite_version!"
-
-
-#*****************************************************************************************
-#***************************************** LCG-CE ****************************************
-#*****************************************************************************************
-
-if ( echo " ${NODE_TYPE_LIST} " | egrep -q "CE" ) && ( ! echo " ${NODE_TYPE_LIST} " | egrep -q 'creamCE' ); then
-
-	if [ ! -d /tmp/sge/opt/globus/lib/perl/Globus/GRAM/JobManager ]; then
-     		mkdir -p /tmp/sge/opt/globus/lib/perl/Globus/GRAM/JobManager
-     		chmod 700 /tmp/sge/opt/globus/lib/perl/Globus/GRAM/JobManager
-	fi
-
-
-#---*---
-
-###
-### Build JobManager configuration files based on CESGA implementation
-###
-
-	yaimlog INFO "Build JobManager configuration files based on CESGA implementation"
-
-	SGE_JOBMANAGER=$INSTALL_ROOT/globus/lib/perl/Globus/GRAM/JobManager/lcgsge.pm
-	if [ ! -e ${SGE_JOBMANAGER} ]; then
-   		yaimlog ABORT "${SGE_JOBMANAGER} is not installed !!! Without it job management will not work!!! Exiting..."
-   		exit 1
-	fi
-
-	if [ -e ${SGE_JOBMANAGER}.rpmnew ]; then
-   		yaimlog WARNING "New ${SGE_JOBMANAGER} is deployed as .rpmnew in order not to overwrite local JM changes. Old ${SGE_JOBMANAGER} is still in place."
-	fi
-
-	if [ -e ${SGE_JOBMANAGER}.rpmsave ]; then
-   		yaimlog WARNING "Previous ${SGE_JOBMANAGER} is saved as .rpmsave. New ${SGE_JOBMANAGER} is in place."
-	fi
-
-	SGE_JOBMANAGER_CONF=$INSTALL_ROOT/globus/lib/perl/Globus/GRAM/JobManager/lcgsge.conf
-	yaimlog DEBUG "Configuring SGE JM conf file: $SGE_JOBMANAGER_CONF"
-	if [ -e ${SGE_JOBMANAGER_CONF} ]; then
-   		yaimlog WARNING "${SGE_JOBMANAGER_CONF} exists. It will not be changed!. A recommended configuration will be created under /tmp/sge/opt/globus/lib/perl/Globus/GRAM/JobManager/lcgsge.conf. You can copy it manually!"
-   		SGE_JOBMANAGER_CONF="/tmp/sge/opt/globus/lib/perl/Globus/GRAM/JobManager/lcgsge.conf"
-	fi
-
-	cat <<EOF_SGE_JOBMANAGER_CONF > ${SGE_JOBMANAGER_CONF}
-# SGE JM Configuration File
-#
-# SGE paths
-\$SGE_BASE_PATH    = '$SGE_ROOT';
-\$SGE_BIN_PATH     = '$SGE_ROOT/bin/$ARCH';
-# Default values for SGE required complex values
-# In case SGE forces to specify a given set of parameters you can
-# specify the default values in this section
-# If you don't need to define some parameter you should to set it
-# to an empty string or to 0. 
-# Parameters that could be availables in the jdl file
-# These values are only use in case a value is not specified
-# in the jdl file
-# max cpu time
-#\$S_RT           = '10:00:00';
-\$S_RT            = '';
-# max memory
-#\$S_VMEM         = '512M';
-\$S_VMEM          = '';
-# number of processors
-#\$NUM_PROC       = 1;
-\$NUM_PROC        = 0;
-# Extra parameters not available in the jdl file.
-#\$EXTRA          = 'h_fsize=5G,s_cpu=0:10:0';
-\$EXTRA          = '';
-EOF_SGE_JOBMANAGER_CONF
-
-	chmod 644 ${SGE_JOBMANAGER_CONF}
-
-# End of the if for NODE TYPE "CE"
-fi
-
+yaimlog DEBUG "Running SGE Grid Gateway configuration for gLite version $emi_version!"
 
 #*****************************************************************************************
 #***************************************** CreamCE ***************************************
@@ -149,11 +69,7 @@ if ( echo " ${NODE_TYPE_LIST} " | egrep -q "CE" ) && ( echo " ${NODE_TYPE_LIST} 
 ###
 ### Check if sge scripts and BUPDATER are installed
 ###
-        SGE_CREAM_BIN_DIR="/opt/glite/bin"
-        if [ ! -d $SGE_CREAM_BIN_DIR ]; then
-             yaimlog ABORT "$SGE_CREAM_BIN_DIR doesn't exist. Is CREAMCE meta-package installed? Exiting ..."
-             exit 1
-        fi
+	SGE_CREAM_BIN_DIR="/usr/bin"
 
         for sge_scripts in BUpdaterSGE sge_helper sge_cancel.sh sge_hold.sh \
             sge_resume.sh sge_status.sh sge_submit.sh BNotifier; do
@@ -169,25 +85,25 @@ if ( echo " ${NODE_TYPE_LIST} " | egrep -q "CE" ) && ( echo " ${NODE_TYPE_LIST} 
 ###
         BLPARSER_WITH_UPDATER_NOTIFIER=true
 
-        SCRIPT="/opt/glite/etc/blah.config"
+	SCRIPT="/etc/blah.config"
 
         yaimlog DEBUG "Backup $SCRIPT to $SCRIPT.old"
 
 	# backup old file
-  	SCRIPT=/opt/glite/etc/blah.config
+	SCRIPT=/etc/blah.config
   	if [ -f $SCRIPT ]; then
     		cp $SCRIPT $SCRIPT.old
   	fi 
 
   	# local variables definition
-  	mkdir -p /opt/glite/var/log/accounting
-  	chown root.${TOMCAT_USER} /opt/glite/var/log/accounting
-  	chmod 0730 /opt/glite/var/log/accounting
+	mkdir -p /var/log/cream/accounting
+	chown root.${TOMCAT_USER} /var/log/cream/accounting
+	chmod 0730 /var/log/cream/accounting
 
         yaimlog DEBUG "Set up variables to fill $SCRIPT..."
 
 	blah_lrms=sge
-  	blah_accounting_log=/opt/glite/var/log/accounting/blahp.log
+	blah_accounting_log=/var/log/cream/accounting/blahp.log
   	blah_bin=${BATCH_BIN_DIR}
   	blah_conf=
   	blah_spool=${BATCH_LOG_DIR}
@@ -204,8 +120,8 @@ if ( echo " ${NODE_TYPE_LIST} " | egrep -q "CE" ) && ( echo " ${NODE_TYPE_LIST} 
   	blah_blp_port2=
   	row_to_add=""
  
- 	 # New parser
-  	bupdater_bin_path=${GLITE_LOCATION}/bin/BUpdaterSGE
+	 # New parser
+	bupdater_bin_path=/usr/bin/BUpdaterSGE
 
 
 # ---*---
@@ -272,7 +188,8 @@ ${blah_lrms}_BLPport2=$blah_blp_port2
 
 ${blah_lrms}_rootpath=$SGE_ROOT
 ${blah_lrms}_cellname=$SGE_CELL
-${blah_lrms}_helperpath=/opt/glite/bin/sge_helper
+#${blah_lrms}_helperpath=/opt/glite/bin/sge_helper
+#${blah_lrms}_helperpath=/usr/bin/sge_helper
 EOF
 
 
@@ -289,10 +206,10 @@ EOF
 
                 yaimlog DEBUG "Append BNotifier definitions to $SCRIPT..."
 
-    		if [ ! -f ${GLITE_LOCATION_VAR}/blah ]; then
-      			mkdir -p ${GLITE_LOCATION_VAR}/blah
-      			chown tomcat.tomcat ${GLITE_LOCATION_VAR}/blah
-      			chmod 771 ${GLITE_LOCATION_VAR}/blah
+    		if [ ! -f /var/blah ]; then
+      			mkdir -p /var/blah
+      			chown tomcat.tomcat /var/blah
+      			chmod 771 /var/blah
     		fi
     		cat << EOF >> $SCRIPT
 # New parser section
@@ -304,7 +221,7 @@ async_notification_host=localhost
 purge_interval=5000000
 
 #Updater location
-bupdater_path=/opt/glite/bin/BUpdaterSGE
+bupdater_path=/usr/bin/BUpdaterSGE
 
 #Notifier location
 bnotifier_path=${GLITE_LOCATION}/bin/BNotifier
@@ -319,13 +236,15 @@ bnotifier_pidfile=/var/tmp/cream_tomcat_bnotifier.pid
 bupdater_debug_level=2
 
 #Updater debug log file
-bupdater_debug_logfile=${GLITE_LOCATION_VAR}/log/glite-ce-bupdater.log
+#bupdater_debug_logfile=${GLITE_LOCATION_VAR}/log/glite-ce-bupdater.log
+bupdater_debug_logfile=/var/log/cream/glite-ce-bupdater.log
 
 #Notifier debug level
 bnotifier_debug_level=2
 
 #Notifier debug log file
-bnotifier_debug_logfile=${GLITE_LOCATION_VAR}/log/glite-ce-bnotifier.log
+#bnotifier_debug_logfile=${GLITE_LOCATION_VAR}/log/glite-ce-bnotifier.log
+bnotifier_debug_logfile=/var/log/cream/glite-ce-bnotifier.log
 
 blah_children_restart_interval=0
 
@@ -352,7 +271,8 @@ EOF
         yaimlog DEBUG "Set up $SCRIPT..."
 
   	cat << EOF > $SCRIPT
-${GLITE_LOCATION_LOG}/accounting/blahp.log {
+#${GLITE_LOCATION_LOG}/accounting/blahp.log {
+/var/log/cream/accounting/blahp.log {
         copytruncate
         rotate 50
         size = 10M
@@ -376,7 +296,8 @@ EOF
 		yaimlog DEBUG "Set up $SCRIPT..."
 
     		cat << EOF > $SCRIPT
-${GLITE_LOCATION_LOG}/glite-ce-bupdater.log {
+#${GLITE_LOCATION_LOG}/glite-ce-bupdater.log {
+/var/log/cream/glite-ce-bupdater.log {
         copytruncate
         rotate 50
         size = 10M
@@ -389,7 +310,8 @@ EOF
 		yaimlog DEBUG "Set up $SCRIPT..."
 
     		cat << EOF > $SCRIPT
-${GLITE_LOCATION_LOG}/glite-ce-bnotifier.log  
+#${GLITE_LOCATION_LOG}/glite-ce-bnotifier.log
+/var/log/cream/glite-ce-bnotifier.log    
  {
         copytruncate
         rotate 50
@@ -416,13 +338,15 @@ EOF
 ### Check content of /opt/glite/etc/lcas/lcas-suexec.db
 ###
 
-	LCAS_SUEXEC_DB="${GLITE_LOCATION}/etc/lcas/lcas-suexec.db"
+	#LCAS_SUEXEC_DB="${GLITE_LOCATION}/etc/lcas/lcas-suexec.db"
+	LCAS_SUEXEC_DB="/etc/lcas/lcas-suexec.db"
 	moddir="/opt/glite/lib64/modules"
 	my_batch_sys="sge"
 
 	for sge_blah_script in ${my_batch_sys}_status.sh ${my_batch_sys}_cancel.sh \
             ${my_batch_sys}_hold.sh ${my_batch_sys}_resume.sh ${my_batch_sys}_submit.sh; do 
-        	LCAS_SUEXEC_DB_EMPTY=`cat $LCAS_SUEXEC_DB | grep "${GLITE_LOCATION}/bin/$sge_blah_script"`
+        	#LCAS_SUEXEC_DB_EMPTY=`cat $LCAS_SUEXEC_DB | grep "${GLITE_LOCATION}/bin/$sge_blah_script"`
+		LCAS_SUEXEC_DB_EMPTY=`cat $LCAS_SUEXEC_DB | grep "/usr/bin/$sge_blah_script"`
         	if [ "X$LCAS_SUEXEC_DB_EMPTY" == "X" ]; then
              		break
         	fi
@@ -435,7 +359,8 @@ EOF
 
         	cat << EOF > $LCAS_SUEXEC_DB
 pluginname=${moddir}/lcas_voms.mod,pluginargs="-vomsdir /etc/grid-security/vomsdir/ -certdir /etc/grid-security/certificates -authfile ${GRIDMAPFILE} -authformat simple -use_user_dn"
-pluginname=${moddir}/lcas_check_executable.mod,pluginargs="-exec /bin/pwd:/bin/echo:/usr/bin/readlink:/bin/kill:${GLITE_LOCATION}/bin/BPRclient:/bin/rm:/bin/cp:/usr/bin/id:/bin/cat:/usr/bin/groups:/usr/bin/whoami:${GLITE_LOCATION}/etc/glite-ce-cream/cream-glexec.sh:${GLITE_LOCATION}/bin/blah_job_registry_lkup:${GLITE_LOCATION}/bin/${my_batch_sys}_submit.sh:${GLITE_LOCATION}/bin/${my_batch_sys}_status.sh:${GLITE_LOCATION}/bin/${my_batch_sys}_cancel.sh:${GLITE_LOCATION}/bin/${my_batch_sys}_hold.sh:${GLITE_LOCATION}/bin/${my_batch_sys}_resume.sh:${GLITE_LOCATION}/bin/glite-cream-createsandboxdir"
+#pluginname=${moddir}/lcas_check_executable.mod,pluginargs="-exec /bin/pwd:/bin/echo:/usr/bin/readlink:/bin/kill:${GLITE_LOCATION}/bin/BPRclient:/bin/rm:/bin/cp:/usr/bin/id:/bin/cat:/usr/bin/groups:/usr/bin/whoami:${GLITE_LOCATION}/etc/glite-ce-cream/cream-glexec.sh:${GLITE_LOCATION}/bin/blah_job_registry_lkup:${GLITE_LOCATION}/bin/${my_batch_sys}_submit.sh:${GLITE_LOCATION}/bin/${my_batch_sys}_status.sh:${GLITE_LOCATION}/bin/${my_batch_sys}_cancel.sh:${GLITE_LOCATION}/bin/${my_batch_sys}_hold.sh:${GLITE_LOCATION}/bin/${my_batch_sys}_resume.sh:${GLITE_LOCATION}/bin/glite-cream-createsandboxdir"
+pluginname=${moddir}/lcas_check_executable.mod,pluginargs="-exec /bin/pwd:/bin/echo:/usr/bin/readlink:/bin/kill:/usr/bin/BPRclient:/bin/rm:/bin/cp:/usr/bin/id:/bin/cat:/usr/bin/groups:/usr/bin/whoami:/usr/etc/glite-ce-cream/cream-glexec.sh:/usr/bin/blah_job_registry_lkup:/usr/bin/${my_batch_sys}_submit.sh:/usr/bin/${my_batch_sys}_status.sh:/usr/bin/${my_batch_sys}_cancel.sh:/usr/bin/${my_batch_sys}_hold.sh:/usr/bin/${my_batch_sys}_resume.sh:/usr/bin/glite-cream-createsandboxdir"
 EOF
 	fi
 
