*** empty log message ***

diff --git a/config/functions/config_sgeenv b/config/functions/config_sgeenv
--- a/config/functions/config_sgeenv
+++ b/config/functions/config_sgeenv
@@ -44,20 +44,6 @@ function config_sgeenv(){
 INSTALL_ROOT=${INSTALL_ROOT:-/opt}
 
 ###
-### Some changes were introduced in SGEV62u1
-### Therefore, we need to know the SGE version
-###
-
-yaimlog DEBUG "Get SGE version"
-
-SGE_VERSION=`${SGE_ROOT}/bin/lx26-x86/qstat -help | head -n 1 | cut -f2 -d ' ' | cut -f1 -d 'u'`
-SGEV62=`echo "$SGE_VERSION >= 6.2 " | bc`
-
-
-#---*---
-
-
-###
 ### Create SGE dir structure for client
 ###
 
@@ -101,7 +87,7 @@ fi
 BOOTSTRAP_FILE=${SGE_ROOT}/${SGE_CELL}/common/bootstrap
 yaimlog DEBUG "Configuring SGE ${BOOTSTRAP_FILE} file"
 if [ -e ${BOOTSTRAP_FILE} ]; then
-     yaimlog WARNING "${BOOTSTRAP_FILE} exists! It will be overwritten with your current definitions"
+     yaimlog DEBUG "${BOOTSTRAP_FILE} exists! It will be overwritten with your current definitions"
 fi
 
 cat <<EOF_BOOTSTRAP_FILE > ${BOOTSTRAP_FILE}
@@ -128,68 +114,11 @@ ACT_QMASTER_FILE=${SGE_ROOT}/${SGE_CELL}/common/act_qmaster
 yaimlog DEBUG "Configuring SGE ${ACT_QMASTER_FILE} file"
 if [ -e ${ACT_QMASTER_FILE} ]; then
    OLD_BATCH_SERVER=`cat ${ACT_QMASTER_FILE}`
-   yaimlog WARNING "${ACT_QMASTER_FILE} exists! New value (${BATCH_SERVER}) will overwrite old value (${OLD_BATCH_SERVER})"
+   yaimlog DEBUG "${ACT_QMASTER_FILE} exists! New value (${BATCH_SERVER}) will overwrite old value (${OLD_BATCH_SERVER})"
 fi
 cat <<EOF_ACT_QMASTER_FILE > ${ACT_QMASTER_FILE}
 ${BATCH_SERVER}
 EOF_ACT_QMASTER_FILE
-
-
-#---*---
-
-if [ "X${SGEV62}" == "X1" ]; then
-	CLUSTER_NAME_FILE=${SGE_ROOT}/${SGE_CELL}/common/cluster_name
-	yaimlog DEBUG "Configuring SGE ${CLUSTER_NAME_FILE} file"
-	if [ -e ${CLUSTER_NAME_FILE} ]; then
-   		OLD_CLUSTER_NAME=`cat ${CLUSTER_NAME_FILE}`
-   		yaimlog WARNING "${CLUSTER_NAME_FILE} exists! New value (p${SGE_QMASTER}) will overwrite old value (${OLD_CLUSTER_NAME})"
-	fi
-	cat <<EOF_CLUSTER_NAME_FILE > ${CLUSTER_NAME_FILE}
-p${SGE_QMASTER}
-EOF_CLUSTER_NAME_FILE
-fi 
-
-
-#---*---
-
-
-###
-### Create /etc/profile.d/sge.sh
-###
-
-yaimlog INFO "Build the scripts which set the proper SGE environment"
-
-SGE_SHENV_FILE=/etc/profile.d/sge.sh
-yaimlog DEBUG "Create $SGE_SHENV_FILE file"
-if [ -e ${SGE_SHENV_FILE} ]; then
-   yaimlog WARNING "${SGE_SHENV_FILE} exists. It will be overwritten with your current definitions."
-fi
-cat <<EOF_SGE_SHENV_FILE > ${SGE_SHENV_FILE}
-# Define SGE_ROOT directory and SGE commands
-export SGE_ROOT=${SGE_ROOT}
-export SGE_CELL=${SGE_CELL}
-. ${SGE_ROOT}/${SGE_CELL}/common/settings.sh
-EOF_SGE_SHENV_FILE
-
-
-#---*---
-
-
-###
-### Create /etc/profile.d/sge.csh
-###
-
-SGE_CSHENV_FILE=/etc/profile.d/sge.csh
-yaimlog DEBUG "Create $SGE_CSHENV_FILE file"
-if [ -e ${SGE_CSHENV_FILE} ]; then
-   yaimlog WARNING "${SGE_CSHENV_FILE} exists. It will be overwritten with your current definitions."
-fi
-cat <<EOF_SGE_CSHENV_FILE > ${SGE_CSHENV_FILE}
-# Define SGE_ROOT directory and SGE commands
-setenv SGE_ROOT "${SGE_ROOT}"
-setenv SGE_CELL "${SGE_CELL}"
-source ${SGE_ROOT}/${SGE_CELL}/common/settings.csh
-EOF_SGE_CSHENV_FILE
 
 
 #---*---
@@ -204,7 +133,7 @@ SGE_SHSETTING_FILE=${SGE_ROOT}/${SGE_CELL}/common/settings.sh
 yaimlog DEBUG "Check if ${SGE_SHSETTING_FILE} exists!"
 
 if [ -e ${SGE_SHSETTING_FILE} ]; then
-     yaimlog WARNING "${SGE_SHSETTING_FILE} exists. It will be overwritten with your current definitions."
+     yaimlog DEBUG "${SGE_SHSETTING_FILE} exists. It will be overwritten with your current definitions."
 fi
 
 cat <<EOF_SGE_SHSETTING_FILE > ${SGE_SHSETTING_FILE}
@@ -233,7 +162,7 @@ export \$shlib_path_name
 unset ARCH DEFAULTMANPATH MANTYPE shlib_path_name
 EOF_SGE_SHSETTING_FILE
 
-chmod 644 ${SGE_SHSETTING_FILE}; source ${SGE_SHENV_FILE}
+chmod 644 ${SGE_SHSETTING_FILE}
 
 
 #---*---
@@ -244,10 +173,13 @@ chmod 644 ${SGE_SHSETTING_FILE}; source ${SGE_SHENV_FILE}
 ###
 
 SGE_CSHSETTING_FILE=${SGE_ROOT}/${SGE_CELL}/common/settings.csh
+
 yaimlog DEBUG "Check if ${SGE_CSHSETTING_FILE} exists. If not, create it!"
+
 if [ -e ${SGE_CSHSETTING_FILE} ]; then
-     yaimlog WARNING "${SGE_CSHSETTING_FILE} exists. It will be overwritten with your current definitions."
+     yaimlog DEBUG "${SGE_CSHSETTING_FILE} exists. It will be overwritten with your current definitions."
 fi
+
 cat <<EOF_SGE_CSHSETTING_FILE > ${SGE_CSHSETTING_FILE}
 #!/bin/tcsh
 setenv SGE_ROOT ${SGE_ROOT}
@@ -275,6 +207,7 @@ else
 endif
 unset ARCH DEFAULTMANPATH MANTYPE shlib_path_name
 EOF_SGE_CSHSETTING_FILE
+
 chmod 644 ${SGE_CSHSETTING_FILE}
 
 
@@ -282,18 +215,111 @@ chmod 644 ${SGE_CSHSETTING_FILE}
 
 
 ###
-### Link SGE binaries to lx26-x86 (original compilation)
+### Create /etc/profile.d/sge.sh
 ###
 
-yaimlog DEBUG "Link binaries to lx26-x86 (original compilation)"
+yaimlog INFO "Build the scripts which set the proper SGE environment"
+
+SGE_SHENV_FILE=/etc/profile.d/sge.sh
+
+yaimlog DEBUG "Create $SGE_SHENV_FILE file"
+
+if [ -e ${SGE_SHENV_FILE} ]; then
+   yaimlog DEBUG "${SGE_SHENV_FILE} exists. It will be overwritten with your current definitions."
+fi
+
+cat <<EOF_SGE_SHENV_FILE > ${SGE_SHENV_FILE}
+# Define SGE_ROOT directory and SGE commands
+export SGE_ROOT=${SGE_ROOT}
+export SGE_CELL=${SGE_CELL}
+. ${SGE_ROOT}/${SGE_CELL}/common/settings.sh
+EOF_SGE_SHENV_FILE
+
+chmod 644 ${SGE_SHENV_FILE}
+
+source ${SGE_SHENV_FILE}
+
+
+#---*---
+
+
+###
+### Create /etc/profile.d/sge.csh
+###
+
+SGE_CSHENV_FILE=/etc/profile.d/sge.csh
+
+yaimlog DEBUG "Create $SGE_CSHENV_FILE file"
+
+if [ -e ${SGE_CSHENV_FILE} ]; then
+   yaimlog DEBUG "${SGE_CSHENV_FILE} exists. It will be overwritten with your current definitions."
+fi
+
+cat <<EOF_SGE_CSHENV_FILE > ${SGE_CSHENV_FILE}
+# Define SGE_ROOT directory and SGE commands
+setenv SGE_ROOT "${SGE_ROOT}"
+setenv SGE_CELL "${SGE_CELL}"
+source ${SGE_ROOT}/${SGE_CELL}/common/settings.csh
+EOF_SGE_CSHENV_FILE
+
+chmod 644 ${SGE_CSHENV_FILE}
+
+
+#---*---
+
+
+###
+### Some changes were introduced in SGEV62u1
+### Therefore, we need to know the SGE version
+###
+
+yaimlog DEBUG "Get SGE version and link SGE binaries to lx26-x86 (original compilation)"
 
 ARCH=`$SGE_ROOT/util/arch`
-ARCH_DEFAULT=lx26-x86
-if [ "X$ARCH" != "X$ARCH_DEFAULT" ]
-then
-   ln -s $SGE_ROOT/bin/$ARCH_DEFAULT $SGE_ROOT/bin/$ARCH
-   ln -s $SGE_ROOT/utilbin/$ARCH_DEFAULT $SGE_ROOT/utilbin/$ARCH
-   ln -s $SGE_ROOT/lib/$ARCH_DEFAULT $SGE_ROOT/lib/$ARCH
+if [ "X$ARCH" != "X" ]; then
+     QSTAT="${SGE_ROOT}/bin/$ARCH/qstat"
+else
+     yaimlog ABORT "Unable to get machine arch..."
+     exit 1
+fi
+
+ARCH_DEFAULT="lx26-x86"
+QSTAT_DEFAULT="${SGE_ROOT}/bin/${ARCH_DEFAULT}/qstat"
+
+if [ "X$QSTAT" != "X$QSTAT_DEFAULT" ]; then
+     if [ -x $QSTAT ]; then
+     	  SGE_VERSION=`$QSTAT -help | head -n 1 | cut -f2 -d ' ' | cut -f1 -d 'u'`
+     elif [ -x $QSTAT_DEFAULT ]; then
+          ln -s $SGE_ROOT/bin/$ARCH_DEFAULT $SGE_ROOT/bin/$ARCH
+          ln -s $SGE_ROOT/utilbin/$ARCH_DEFAULT $SGE_ROOT/utilbin/$ARCH
+          ln -s $SGE_ROOT/lib/$ARCH_DEFAULT $SGE_ROOT/lib/$ARCH         
+          SGE_VERSION=`$QSTAT_DEFAULT -help | head -n 1 | cut -f2 -d ' ' | cut -f1 -d 'u'`
+     else
+          yaimlog ABORT "Unable to get SGE version running qstat. Is SGE client installed?..."
+     fi
+else
+     SGE_VERSION=`$QSTAT -help | head -n 1 | cut -f2 -d ' ' | cut -f1 -d 'u'`
+fi
+SGEV62=`echo "$SGE_VERSION >= 6.2 " | bc`
+
+
+#---*---
+
+
+###
+### Create cluster file
+###
+
+if [ "X${SGEV62}" == "X1" ]; then
+        CLUSTER_NAME_FILE=${SGE_ROOT}/${SGE_CELL}/common/cluster_name
+        yaimlog DEBUG "Configuring SGE ${CLUSTER_NAME_FILE} file"
+        if [ -e ${CLUSTER_NAME_FILE} ]; then
+                OLD_CLUSTER_NAME=`cat ${CLUSTER_NAME_FILE}`
+                yaimlog DEBUG "${CLUSTER_NAME_FILE} exists! New value (p${SGE_QMASTER}) will overwrite old value (${OLD_CLUSTER_NAME})"
+        fi
+        cat <<EOF_CLUSTER_NAME_FILE > ${CLUSTER_NAME_FILE}
+p${SGE_QMASTER}
+EOF_CLUSTER_NAME_FILE
 fi
 
 
@@ -305,8 +331,10 @@ fi
 ###
 
 SERVICES_FILE="/etc/services"
+
 yaimlog DEBUG "Modify ${SERVICES_FILE} file and add the appropriate ports for SGE daemons"
-PORT1=`grep "${SGE_QMASTER}/tcp" ${SERVICES_FILE} | grep -v sge`
+
+PORT1=`grep " +${SGE_QMASTER}/tcp" ${SERVICES_FILE} | grep -v sge`
 if [ "X${PORT1}" != "X" ]; then
      yaimlog ABORT "Port ${SGE_QMASTER}/tcp is already used by other service. Check ${SERVICES_FILE}"
      exit 1
@@ -324,7 +352,7 @@ else
      fi
 fi
 
-PORT2=`grep "${SGE_EXECD}/tcp" ${SERVICES_FILE} | grep -v sge`
+PORT2=`grep " +${SGE_EXECD}/tcp" ${SERVICES_FILE} | grep -v sge`
 if [ "X${PORT2}" != "X" ]; then
      yaimlog ABORT "Port ${SGE_EXECD}/tcp is already used by other service. Check ${SERVICES_FILE}"
      exit 1
